name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/unit
          pytest tests/integration

      - name: Build Docker image
        run: |
          docker build -t lavagante-project .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag lavagante-project:latest ${{ secrets.DOCKER_USERNAME }}/lavagante-project:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/lavagante-project:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
          echo "Deploying to production server..."
          # Add deployment commands here
          # e.g., ssh user@server "docker pull ${{ secrets.DOCKER_USERNAME }}/lavagante-project:latest && docker run -d ${{ secrets.DOCKER_USERNAME }}/lavagante-project:latest"